import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import bg from "../../public/img/star-wars-bg.jpg";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Star Wars",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <div
          className="h-screen"
          style={{
            backgroundImage: `url(${bg.src})`,
            // backgroundRepeat: "no-repeat",
            backgroundSize: "cover",
            // width: "100%",
            // height: "100vh",
          }}
        >
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
