import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Star Wars",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        {/* <div
          className="h-screen"
          style={{
            backgroundImage: `url(${bg.src})`,
            backgroundSize: "auto 100%",
          }}
        > */}
        <Navbar />
        {children}
        {/* </div> */}
      </body>
    </html>
  );
}
